on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./octions/issues/create-comment
        id: my_step_id
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          body: hello!
