on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npx cloc . > cloc.txt
      - uses: ./octions/issues/create-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          body: hello!
      - uses: ./octions/issues/create-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          body: FILE::cloc.txt
